# HACHI Demo: Human-AI Co-design for Clinical Prediction Models

This notebook demonstrates the HACHI framework using a simple clinical scenario: **Flu Detection** from patient notes.

## What You'll Learn

1. **Step 1**: Extract keyphrases from clinical notes using an LLM
2. **Step 2**: Train an ensemble of concept bottleneck models
3. **Step 3**: Review results in an interactive HTML viewer

## Prerequisites
Set up your virtual environment and install the python packages in `requirements.txt`.

You need an API key from one of these providers:
- **OpenAI**: Get your key at https://platform.openai.com/api-keys
- **Anthropic (Claude)**: Get your key at https://console.anthropic.com/

## Estimated Cost

This demo uses a small dataset (40 samples) and minimal training to keep costs low:
- ~$0.50-2.00 with GPT-4o-mini
- ~$1.00-3.00 with Claude Haiku

## Setup

First, configure your API key. Create a `.env` file in the project root or set it directly below.

In [12]:
import os
import sys
from pathlib import Path

# Fix for Jupyter's event loop (allows nested asyncio.run() calls)
import nest_asyncio
nest_asyncio.apply()

# Add project root to path (parent of notebooks/)
notebook_dir = Path.cwd()
if notebook_dir.name == "notebooks":
    project_root = notebook_dir.parent
else:
    project_root = notebook_dir
sys.path.insert(0, str(project_root))

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
# ============================================
# CONFIGURE YOUR API KEY HERE
# ============================================
# Option 1: Set directly (not recommended for shared notebooks)
# os.environ["OPENAI_API_KEY"] = "sk-..."
# os.environ["ANTHROPIC_API_KEY"] = "sk-ant-..."

# Option 2: Create a .env file in the project root with:
# OPENAI_API_KEY=sk-...
# or
# ANTHROPIC_API_KEY=sk-ant-...

# Verify API key is set
if os.getenv("OPENAI_API_KEY"):
    print("OpenAI API key found")
    LLM_MODEL = "gpt-4o-mini"  # Cost-effective option
elif os.getenv("ANTHROPIC_API_KEY"):
    print("Anthropic API key found")
    LLM_MODEL = "claude-haiku-4-5-20251001"  # Cost-effective option
else:
    raise ValueError(
        "No API key found! Please set OPENAI_API_KEY or ANTHROPIC_API_KEY\n"
        "Either in your .env file or by uncommenting the lines above."
    )

print(f"Using model: {LLM_MODEL}")

OpenAI API key found
Using model: gpt-4o-mini

## Load the Demo Dataset

Our demo dataset contains 40 synthetic patient notes for flu detection (y=1: flu, y=0: no flu).

In [3]:
import pandas as pd
import numpy as np

pd.set_option('display.max_colwidth', 200)

# Load the demo dataset
data_path = "data/demo_patients.csv"
df = pd.read_csv(data_path)

print(f"Dataset shape: {df.shape}")
print(f"=====Outcome distribution=======")
print(df['y'].value_counts())
print("=====Example patient record======")
print(df['sentence'].iloc[0])

Dataset shape: (40, 3)
=====Outcome distribution=======
y
0    24
1    16
Name: count, dtype: int64
=====Example patient record======
Chief complaint: flu-like symptoms
HPI: 54yo female. Reports high body temperature, runny nose, fever of 101.5F, dry cough.
Exam: Temperature 101.2F. Pharynx erythematous. Mild tachycardia.
Assessment: Influenza likely. Recommend rest, fluids, and symptomatic treatment.

In [ ]:
# Create output directories
output_dir = Path("output")
output_dir.mkdir(exist_ok=True)

# Create train/test split indices
np.random.seed(42)
n_samples = len(df)
indices = np.arange(n_samples)
np.random.shuffle(indices)

# 70% train, 30% test
train_size = int(0.7 * n_samples)
train_indices = indices[:train_size]
test_indices = indices[train_size:]

# Save indices file
indices_df = pd.DataFrame({
    'idx': list(train_indices) + list(test_indices),
    'partition': ['train'] * len(train_indices) + ['test'] * len(test_indices)
})

print(f"Train samples: {len(train_indices)}")
print(f"Test samples: {len(test_indices)}")

Train samples: 28
Test samples: 12

---

# Step 1: Extract Keyphrases from Clinical Notes

The first step in HACHI is to extract relevant keyphrases from each clinical note using an LLM. These keyphrases will be used as input features for concept generation.

This step:
1. Sends each note to the LLM with a keyphrase extraction prompt
2. The LLM identifies clinically relevant terms and phrases
3. Results are cached to avoid repeated API calls

In [27]:
# Run keyphrase extraction
from src.keyphrase_config import KeyphraseConfig
from src.keyphrase import Keyphrase

# Configure extraction
extract_config = KeyphraseConfig(
    llm_model_type=LLM_MODEL,
    prompt_file="prompts/keyphrases.txt",
    cache_file=str(output_dir / "demo_cache.db"),
    seed=42,
    batch_size=10,
    num_new_tokens=500,
    prompt_placeholder="{note}",
    text_column="sentence",
    is_image=False,
    index_col=None,
    llm_outputs_file=str(output_dir / "keyphrases.csv"),
    log_file=str(output_dir / "log_extract.txt")
)

print("Starting keyphrase extraction...")
print(f"This will process {len(train_indices)} training samples.")

# Run extraction
extractor = Keyphrase(extract_config)
result_df = extractor.extract(df, train_indices)

print(f"\nExtraction complete!")
print(f"Non-empty outputs: {(result_df.llm_output != '').sum()}")

Starting keyphrase extraction...
This will process 28 training samples.
DATASET LEN 28

100%|██████████| 3/3 [00:00<00:00, 182.64it/s]

CACHE HIT
CACHE HIT
CACHE HIT

Extraction complete!
Non-empty outputs: 26

In [28]:
# View sample extractions
result_df[result_df.llm_output != ""].head()

,index,patient_id,sentence,y,llm_output
0,0,FLU-009,"Chief complaint: flu-like symptoms\nHPI: 54yo female. Reports high body temperature, runny nose, fever of 101.5F, dry cough.\nExam: Temperature 101.2F. Pharynx erythematous. Mild tachycardia.\nAss...",1,"high body temperature,runny nose,fever,dry cough,erythematous pharynx,mild tachycardia"
1,1,FLU-003,"Chief complaint: flu-like symptoms\nHPI: 40yo male. Reports nasal congestion, sore throat, fever of 38C, fever of 101.5F.\nExam: Cervical lymphadenopathy. Mild tachycardia. Temperature 101.2F.\nAs...",1,"nasal congestion,sore throat,fever,cervical lymphadenopathy,tachycardia,elevated temperature"
2,2,FLU-010,"Chief complaint: flu-like symptoms\nHPI: 61yo male. Reports sore throat, nasal congestion, fever of 101.5F, body aches and myalgias.\nExam: Mild tachycardia. Pharynx erythematous. Temperature 101....",1,"sore throat,nasal congestion,fever,body aches,myalgias,tachycardia,erythematous pharynx,temperature"
4,4,CTRL-009,Chief complaint: request for lab work\nHPI: 36yo male.\nExam: Temperature 98.6F. No lymphadenopathy.\nAssessment: No acute illness. Continue current management.,0,"normal temperature,no lymphadenopathy,no acute illness"
5,5,CTRL-008,Chief complaint: knee pain after exercise\nHPI: 58yo female.\nExam: Temperature 98.6F. No lymphadenopathy.\nAssessment: No acute illness. Continue current management.,0,normal temperature

---

# Step 2: Train the Ensemble

Now we train an ensemble of concept bottleneck models using the `EnsembleTrainer` class.

The training process:
1. **Baseline initialization**: Generate initial concept candidates from the keyphrases
2. **Iterative refinement**: Add/refine concepts based on model residuals

We use minimal settings to keep API costs low:
- 1 initialization seed
- 1 epoch
- 3 target concepts

This is similar to running `lm()` in R, but for unstructured text data!

In [21]:
# Configure the ensemble trainer
from src.ensemble_trainer import (
    EnsembleTrainer,
    EnsembleConfig,
    ModelConfig,
    LLMConfig,
    DataConfig,
    TrainingConfig,
    ConceptConfig,
)

# Create configuration (similar to specifying a model formula in R)
ensemble_config = EnsembleConfig(
    init_seeds=[1],  # Single seed for demo (use multiple for production)
    model=ModelConfig(
        residual_model_type="l2",
        final_model_type="l1_sklearn",
        cv=3,
    ),
    llm=LLMConfig(
        llm_model=LLM_MODEL,
        max_new_tokens=2000,
        cache_file=str(output_dir / "demo_cache.db"),
    ),
    data=DataConfig(
        text_summary_column="llm_output",
        concept_column="llm_output",
        max_section_length=5000,
    ),
    training=TrainingConfig(
        num_epochs=1,           # Minimal for demo
        num_greedy_epochs=1,
        batch_size=40,
        batch_concept_size=10,
        train_frac=0.7,
    ),
    concept=ConceptConfig(
        goal_num_meta_concepts=3,   # Target number of concepts
        max_meta_concepts=7,        # Max to consider
        num_top_residual_words=30,
        prompt_iter_file="prompts/bayesian_iter.txt",
        prompt_concepts_file="prompts/concept_questions.txt",
        baseline_init_file="prompts/baseline_init.txt",
    ),
)

print("Configuration created!")
print(f"  Model: {LLM_MODEL}")
print(f"  Target concepts: {ensemble_config.concept.goal_num_meta_concepts}")
print(f"  Training epochs: {ensemble_config.training.num_epochs}")

Configuration created!
  Model: gpt-4o-mini
  Target concepts: 3
  Training epochs: 1

In [32]:
# Load the data with keyphrases
train_df = result_df.iloc[train_indices]
train_df["sample_weight"] = 1
train_df

,index,patient_id,sentence,y,llm_output,sample_weight
19,19,CTRL-006,Chief complaint: blood pressure check\nHPI: 47yo male.\nExam: Vital signs normal. Temperature 98.6F.\nAssessment: No acute illness. Continue current management.,0,"normal temperature,no acute illness,vital signs normal",1
16,16,CTRL-019,Chief complaint: blood pressure check\nHPI: 27yo female.\nExam: Temperature 98.6F. Vital signs normal.\nAssessment: No acute illness. Continue current management.,0,"normal temperature,no acute illness,normal vital signs",1
15,15,CTRL-018,Chief complaint: medication refill\nHPI: 50yo female.\nExam: Pharynx clear. No lymphadenopathy.\nAssessment: No acute illness. Continue current management.,0,,1
26,26,CTRL-023,Chief complaint: request for lab work\nHPI: 56yo female.\nExam: Pharynx clear. Vital signs normal.\nAssessment: No acute illness. Continue current management.,0,"pharynx clear,normal vital signs,no acute illness,current management",1
4,4,CTRL-009,Chief complaint: request for lab work\nHPI: 36yo male.\nExam: Temperature 98.6F. No lymphadenopathy.\nAssessment: No acute illness. Continue current management.,0,"normal temperature,no lymphadenopathy,no acute illness",1
12,12,CTRL-007,Chief complaint: mild back pain\nHPI: 27yo male.\nExam: Pharynx clear. Temperature 98.6F.\nAssessment: No acute illness. Continue current management.,0,"normal temperature,clear pharynx,no acute illness,mild back pain",1
37,37,CTRL-001,Chief complaint: blood pressure check\nHPI: 75yo male.\nExam: Temperature 98.6F. No lymphadenopathy.\nAssessment: No acute illness. Continue current management.,0,"normal temperature,no lymphadenopathy,no acute illness,no symptoms",1
27,27,CTRL-017,Chief complaint: blood pressure check\nHPI: 55yo female.\nExam: Temperature 98.6F. Pharynx clear.\nAssessment: No acute illness. Continue current management.,0,"normal temperature,clear pharynx,no acute illness",1
39,39,FLU-007,"Chief complaint: flu-like symptoms\nHPI: 45yo male. Reports runny nose, fever of 101.5F, fever of 38C, headache.\nExam: Temperature 101.2F. Cervical lymphadenopathy. Mild tachycardia.\nAssessment:...",1,"runny nose,fever,headache,cervical lymphadenopathy,tachycardia",1
6,6,CTRL-014,Chief complaint: blood pressure check\nHPI: 57yo male.\nExam: No lymphadenopathy. Temperature 98.6F.\nAssessment: No acute illness. Continue current management.,0,"normal temperature,no lymphadenopathy,no acute illness",1
25,25,CTRL-000,Chief complaint: medication refill\nHPI: 74yo female.\nExam: Vital signs normal. Pharynx clear.\nAssessment: No acute illness. Continue current management.,0,"no acute illness,normal vital signs,clear pharynx",1
9,9,CTRL-016,Chief complaint: knee pain after exercise\nHPI: 48yo female.\nExam: Pharynx clear. No lymphadenopathy.\nAssessment: No acute illness. Continue current management.,0,,1
13,13,CTRL-002,Chief complaint: blood pressure check\nHPI: 58yo female.\nExam: Pharynx clear. Temperature 98.6F.\nAssessment: No acute illness. Continue current management.,0,"normal temperature,clear pharynx",1
31,31,CTRL-011,Chief complaint: routine follow-up visit\nHPI: 48yo female.\nExam: Vital signs normal. Temperature 98.6F.\nAssessment: No acute illness. Continue current management.,0,"normal temperature,no acute illness,routine follow-up,vital signs normal",1
34,34,FLU-008,"Chief complaint: flu-like symptoms\nHPI: 39yo female. Reports high body temperature, body aches and myalgias, fever of 101.5F, fever of 38C.\nExam: Pharynx erythematous. Cervical lymphadenopathy.\...",1,"high body temperature,body aches,myalgias,fever,erythematous pharynx,cervical lymphadenopathy",1
8,8,FLU-004,"Chief complaint: flu-like symptoms\nHPI: 40yo female. Reports coughing, sore throat, high body temperature.\nExam: Temperature 101.2F. Mild tachycardia.\nAssessment: Influenza likely. Recommend re...",1,"cough,sore throat,fever,tachycardia",1
17,17,CTRL-010,Chief complaint: medication refill\nHPI: 67yo male.\nExam: Vital signs normal. Pharynx clear.\nAssessment: No acute illness. Continue current management.,0,"normal vital signs,clear pharynx,no acute illness",1
24,24,CTRL-003,Chief complaint: blood pressure check\nHPI: 56yo female.\nExam: Vital signs normal. Pharynx clear.\nAssessment: No acute illness. Continue current management.,0,"no acute illness,normal vital signs,clear pharynx",1
0,0,FLU-009,"Chief complaint: flu-like symptoms\nHPI: 54yo female. Reports high body temperature, runny nose, fever of 101.5F, dry cough.\nExam: Temperature 101.2F. Pharynx erythematous. Mild tachycardia.\nAss...",1,"high body temperature,runny nose,fever,dry cough,erythematous pharynx,mild tachycardia",1
33,33,FLU-006,"Chief complaint: flu-like symptoms\nHPI: 75yo male. Reports fatigue and malaise, fever of 101.5F, nasal congestion, high body temperature.\nExam: Cervical lymphadenopathy. Pharynx erythematous. Te...",1,"fatigue,malaise,fever,nasal congestion,cervical lymphadenopathy,erythematous pharynx,high body temperature",1
5,5,CTRL-008,Chief complaint: knee pain after exercise\nHPI: 58yo female.\nExam: Temperature 98.6F. No lymphadenopathy.\nAssessment: No acute illness. Continue current management.,0,normal temperature,1
11,11,CTRL-012,Chief complaint: annual physical exam\nHPI: 46yo male.\nExam: Vital signs normal. Temperature 98.6F.\nAssessment: No acute illness. Continue current management.,0,normal temperature,1
1,1,FLU-003,"Chief complaint: flu-like symptoms\nHPI: 40yo male. Reports nasal congestion, sore throat, fever of 38C, fever of 101.5F.\nExam: Cervical lymphadenopathy. Mild tachycardia. Temperature 101.2F.\nAs...",1,"nasal congestion,sore throat,fever,cervical lymphadenopathy,tachycardia,elevated temperature",1
29,29,FLU-000,"Chief complaint: flu-like symptoms\nHPI: 49yo female. Reports fatigue and malaise, headache, sore throat.\nExam: Cervical lymphadenopathy. Pharynx erythematous. Mild tachycardia.\nAssessment: Infl...",1,"fatigue,malaise,headache,sore throat,cervical lymphadenopathy,pharynx erythematous,mild tachycardia",1
21,21,CTRL-015,Chief complaint: request for lab work\nHPI: 31yo female.\nExam: Vital signs normal. Pharynx clear.\nAssessment: No acute illness. Continue current management.,0,"normal vital signs,clear pharynx,no acute illness,current management",1
2,2,FLU-010,"Chief complaint: flu-like symptoms\nHPI: 61yo male. Reports sore throat, nasal congestion, fever of 101.5F, body aches and myalgias.\nExam: Mild tachycardia. Pharynx erythematous. Temperature 101....",1,"sore throat,nasal congestion,fever,body aches,myalgias,tachycardia,erythematous pharynx,temperature",1
30,30,CTRL-022,Chief complaint: knee pain after exercise\nHPI: 33yo female.\nExam: Temperature 98.6F. Pharynx clear.\nAssessment: No acute illness. Continue current management.,0,"normal temperature,clear pharynx",1
36,36,FLU-015,"Chief complaint: flu-like symptoms\nHPI: 38yo male. Reports fever of 101.5F, high body temperature, body aches and myalgias, runny nose, sore throat.\nExam: Cervical lymphadenopathy. Temperature 1...",1,"fever,body aches,myalgias,runny nose,sore throat,cervical lymphadenopathy,high body temperature",1

In [ ]:
# Initialize and train the ensemble
# This is the main training call - similar to model.fit() in sklearn or lm() in R
import logging

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Initialize the trainer
trainer = EnsembleTrainer(
    config=ensemble_config,
    output_dir=str(output_dir),
    seed=42,
)

print("Training ensemble model...")
print("This may take a few minutes depending on the LLM response times.")
print()

# Run the training (async)
training_histories = await trainer.fit(train_df)

print("\nTraining complete!")

Training ensemble model...
This may take a few minutes depending on the LLM response times.

/Users/jean/Documents/Research/HACHI/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:2092: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
/Users/jean/Documents/Research/HACHI/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:2150: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(

[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: We are fitting a concept bottleneck model (CBM) to predict whether or not a patient has the flu from their clinical notes. The goal is to identify interpretable yes/no concepts that clinicians can use to predict probability of having the flu.\n\nA meta-concept must be a yes/no question like \"Does the note mention the patient having...?\".\n\nGiven data analysis, these are the top phrases associated with flu:\nfeature_name,coef\ncervical lymphadenopathy,1.000\nfever,1.000\nsore throat,0.800\nnormal temperature,-0.739\nno acute illness,-0.738\ntachycardia,0.600\nmyalgias,0.600\nbody aches,0.600\nheadache,0.400\nrunny nose,0.400\nerythematous pharynx,0.400\nnasal congestion,0.400\nhigh body temperature,0.400\nclear pharynx,-0.369\nnormal vital signs,-0.369\npharynx erythematous,0.200\nmalaise,0.200\nmild tachycardia,0.200\nfatigue,0.200\nelevated temperature,0.200\ntemperature,0.200\n,-0.185\nno lymphadenopathy,-0.185\npharynx clear,-0.092\ncurrent management,-0.092\nvital signs normal,-0.092\nno symptoms,-0.092\n\n\nYOUR TASK:\nPropose 3 candidate meta-concepts for the CBM.\n\nPropose candidates in JSON format:\n{\n  \"reasoning\": \"Step-by-step explanation\",\n  \"concepts\": [\n    {\n      \"concept\": \"Does the note mention the patient having fever?\",\n      \"is_risk_factor\": true,\n      \"words\": [\"fever\", \"temperature elevated\", \"febrile\"]\n    }\n  ]\n}\n\nFinal answer:"
  ]
}
[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [3.65s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "{\n  \"reasoning\": \"The candidate meta-concepts are derived from the phrases associated with flu symptoms and clinical findings. Each concept is framed as a yes/no question to facilitate interpretation. The 'is_risk_factor' attribute is set to true for symptoms that are positively associated with flu and false for those that indicate absence of flu. The 'words' attribute includes synonyms or related terms to enhance understanding.\",\n  \"concepts\": [\n    {\n      \"concept\": \"Does the note mention the patient having fever?\",\n      \"is_risk_factor\": true,\n      \"words\": [\"fever\", \"temperature elevated\", \"febrile\"]\n    },\n    {\n      \"concept\": \"Does the note mention the patient having sore throat?\",\n      \"is_risk_factor\": true,\n      \"words\": [\"sore throat\", \"throat pain\", \"pharyngitis\"]\n    },\n    {\n      \"concept\": \"Does the note mention the patient having no acute illness?\",\n      \"is_risk_factor\": false,\n      \"words\": [\"no acute illness\", \"no symptoms\", \"no significant findings\"]\n    }\n  ]\n}",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "{\n  \"reasoning\": \"The candidate meta-concepts are derived from the phrases associated with flu symptoms and clinical findings. Each concept is framed as a yes/no question to facilitate interpretation. The 'is_risk_factor' attribute is set to true for symptoms that are positively associated with flu and false for those that indicate absence of flu. The 'words' attribute includes synonyms or related terms to enhance understanding.\",\n  \"concepts\": [\n    {\n      \"concept\": \"Does the note mention the patient having fever?\",\n      \"is_risk_factor\": true,\n      \"words\": [\"fever\", \"temperature elevated\", \"febrile\"]\n    },\n    {\n      \"concept\": \"Does the note mention the patient having sore throat?\",\n      \"is_risk_factor\": true,\n      \"words\": [\"sore throat\", \"throat pain\", \"pharyngitis\"]\n    },\n    {\n      \"concept\": \"Does the note mention the patient having no acute illness?\",\n      \"is_risk_factor\": false,\n      \"words\": [\"no acute illness\", \"no symptoms\", \"no significant findings\"]\n    }\n  ]\n}",
            "additional_kwargs": {
              "parsed": {
                "lc": 1,
                "type": "not_implemented",
                "id": [
                  "src",
                  "llm_response_types",
                  "CandidateConcepts"
                ],
                "repr": "CandidateConcepts(reasoning=\"The candidate meta-concepts are derived from the phrases associated with flu symptoms and clinical findings. Each concept is framed as a yes/no question to facilitate interpretation. The 'is_risk_factor' attribute is set to true for symptoms that are positively associated with flu and false for those that indicate absence of flu. The 'words' attribute includes synonyms or related terms to enhance understanding.\", concepts=[CandidateConcept(concept='Does the note mention the patient having fever?', is_risk_factor=True, words=['fever', 'temperature elevated', 'febrile']), CandidateConcept(concept='Does the note mention the patient having sore throat?', is_risk_factor=True, words=['sore throat', 'throat pain', 'pharyngitis']), CandidateConcept(concept='Does the note mention the patient having no acute illness?', is_risk_factor=False, words=['no acute illness', 'no symptoms', 'no significant findings'])])"
              },
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 229,
                "prompt_tokens": 606,
                "total_tokens": 835,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_name": "gpt-4o-mini-2024-07-18",
              "system_fingerprint": "fp_aa2771c053",
              "id": "chatcmpl-Dpa6EFvi5ZfEv1nRTCZ4YVJfctmBa",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run--c356de79-c479-4aa4-94c6-c48b84f47316-0",
            "usage_metadata": {
              "input_tokens": 606,
              "output_tokens": 229,
              "total_tokens": 835,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 229,
      "prompt_tokens": 606,
      "total_tokens": 835,
      "completion_tokens_details": {
        "accepted_prediction_tokens": 0,
        "audio_tokens": 0,
        "reasoning_tokens": 0,
        "rejected_prediction_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": 0,
        "cached_tokens": 0
      }
    },
    "model_name": "gpt-4o-mini-2024-07-18",
    "system_fingerprint": "fp_aa2771c053",
    "id": "chatcmpl-Dpa6EFvi5ZfEv1nRTCZ4YVJfctmBa",
    "service_tier": "default"
  },
  "run": null,
  "type": "LLMResult"
}
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [1ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [3.65s] Exiting Chain run with output:
[outputs]
DATASET LEN 28

  0%|          | 0/1 [00:00<?, ?it/s]

[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs][chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]

[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nnormal temperature,clear pharynx\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nnormal temperature,no acute illness,routine follow-up,vital signs normal\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nhigh body temperature,body aches,myalgias,fever,erythematous pharynx,cervical lymphadenopathy\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\ncough,sore throat,fever,tachycardia\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nnormal vital signs,clear pharynx,no acute illness\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nno acute illness,normal vital signs,clear pharynx\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nhigh body temperature,runny nose,fever,dry cough,erythematous pharynx,mild tachycardia\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nfatigue,malaise,fever,nasal congestion,cervical lymphadenopathy,erythematous pharynx,high body temperature\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\npharynx clear,normal vital signs,no acute illness,current management\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nnormal temperature\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nnormal temperature\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nnasal congestion,sore throat,fever,cervical lymphadenopathy,tachycardia,elevated temperature\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nfatigue,malaise,headache,sore throat,cervical lymphadenopathy,pharynx erythematous,mild tachycardia\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nnormal temperature,no lymphadenopathy,no acute illness\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nnormal vital signs,clear pharynx,no acute illness,current management\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nnormal temperature,no lymphadenopathy,no acute illness,no symptoms\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nsore throat,nasal congestion,fever,body aches,myalgias,tachycardia,erythematous pharynx,temperature\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nnormal temperature,clear pharynx\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having sore throat?\n3 - Does the note mention the patient having no acute illness?\n\n\nClinical notes:\nfever,body aches,myalgias,runny nose,sore throat,cervical lymphadenopathy,high body temperature\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [

100%|██████████| 1/1 [00:02<00:00,  2.58s/it]

[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [2.51s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "{\"reasoning\":null,\"extractions\":[{\"question\":1,\"reasoning\":\"The note states 'normal temperature', which indicates the patient does not have a fever.\",\"answer\":0},{\"question\":2,\"reasoning\":\"The note mentions 'clear pharynx', which suggests there is no sore throat present.\",\"answer\":0},{\"question\":3,\"reasoning\":\"The note explicitly states 'no acute illness'.\",\"answer\":1}]}",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "{\"reasoning\":null,\"extractions\":[{\"question\":1,\"reasoning\":\"The note states 'normal temperature', which indicates the patient does not have a fever.\",\"answer\":0},{\"question\":2,\"reasoning\":\"The note mentions 'clear pharynx', which suggests there is no sore throat present.\",\"answer\":0},{\"question\":3,\"reasoning\":\"The note explicitly states 'no acute illness'.\",\"answer\":1}]}",
            "additional_kwargs": {
              "parsed": {
                "lc": 1,
                "type": "not_implemented",
                "id": [
                  "src",
                  "llm_response_types",
                  "ExtractResponseList"
                ],
                "repr": "ExtractResponseList(reasoning=None, extractions=[ExtractResponse(question=1, reasoning=\"The note states 'normal temperature', which indicates the patient does not have a fever.\", answer=0.0), ExtractResponse(question=2, reasoning=\"The note mentions 'clear pharynx', which suggests there is no sore throat present.\", answer=0.0), ExtractResponse(question=3, reasoning=\"The note explicitly states 'no acute illness'.\", answer=1.0)])"
              },
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 89,
                "prompt_tokens": 359,
                "total_tokens": 448,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_name": "gpt-4o-mini-2024-07-18",
              "system_fingerprint": "fp_d0b314e02e",
              "id": "chatcmpl-Dpa6IjMt4TnLVC21JXDS2neZUIDiq",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run--03ebd433-b70d-4602-85f4-c3b8d83f07f7-0",
            "usage_metadata": {
              "input_tokens": 359,
              "output_tokens": 89,
              "total_tokens": 448,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 89,
      "prompt_tokens": 359,
      "total_tokens": 448,
      "completion_tokens_details": {
        "accepted_prediction_tokens": 0,
        "audio_tokens": 0,
        "reasoning_tokens": 0,
        "rejected_prediction_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": 0,
        "cached_tokens": 0
      }
    },
    "model_name": "gpt-4o-mini-2024-07-18",
    "system_fingerprint": "fp_d0b314e02e",
    "id": "chatcmpl-Dpa6IjMt4TnLVC21JXDS2neZUIDiq",
    "service_tier": "default"
  },
  "run": null,
  "type": "LLMResult"
}
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [12ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [12ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [12ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [12ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [12ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [12ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [12ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [12ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [13ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [12ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [12ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [13ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.55s] Exiting Chain run with output:
[outputs]
test_auc 0.5833333333333333

/Users/jean/Documents/Research/HACHI/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jean/Documents/Research/HACHI/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/jean/Documents/Research/HACHI/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jean/Documents/Research/HACHI/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:2092: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
/Users/jean/Documents/Research/HACHI/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:2150: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(

[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: We are fitting a concept bottleneck model (CBM) to predict influenza (flu). We have 2 meta-concepts so far:\n* X0 = Does the note mention the patient having fever? \n* X1 = Does the note mention the patient having sore throat? \n\n\nTo improve the CBM, these are the top phrases from the residual model:\nfeature_name,coef\ncervical lymphadenopathy,1.000\nno acute illness,-0.879\nnormal temperature,-0.803\ntachycardia,0.780\nmyalgias,0.638\nbody aches,0.638\nnasal congestion,0.523\nerythematous pharynx,0.523\nclear pharynx,-0.379\nheadache,0.372\nrunny nose,0.372\nhigh body temperature,0.372\nnormal vital signs,-0.369\ntemperature,0.267\nelevated temperature,0.257\nvital signs normal,-0.236\n,-0.179\nno lymphadenopathy,-0.179\nmild tachycardia,0.115\npharynx erythematous,0.115\nmalaise,0.115\nfatigue,0.115\npharynx clear,-0.095\ncurrent management,-0.095\nno symptoms,-0.085\n\n\nA positive coefficient means higher flu risk. A negative coefficient means lower flu risk.\n\nCreate candidates for the 3th meta-concept. Be systematic and consider all listed concepts.\n\nPropose at least ten candidates in JSON format:\n{\n  \"reasoning\": \"Step-by-step explanation\",\n  \"concepts\": [\n    {\n      \"concept\": \"Does the note mention the patient having body aches?\",\n      \"is_risk_factor\": true,\n      \"words\": [\"body aches\", \"myalgias\", \"muscle pain\"]\n    }\n  ]\n}"
  ]
}

In [ ]:
# Display training results
print("Training Results")
print("=" * 60)

for init_seed, history in training_histories.items():
    print(f"\nModel (seed={init_seed}):")
    print(f"  Number of iterations: {history.num_iters}")
    print(f"  Final AUC: {history.get_last_auc():.3f}")
    
    print(f"\n  Learned Concepts:")
    for i, concept in enumerate(history.get_last_concepts()):
        coef = history._coefs[-1][i] if history._coefs else "N/A"
        print(f"    {i+1}. {concept['concept']}")
        if isinstance(coef, (int, float)):
            print(f"       Coefficient: {coef:.3f}")

---

# Step 3: Review Results in HTML Viewer

HACHI provides an interactive HTML viewer to explore:
- Individual patient notes and their concept assignments
- Model performance metrics
- Concept coefficients and their interpretations
- Hierarchical clustering of concepts

To generate the viewer, run these commands from the project root:

In [ ]:
# Save viewer configuration
import json

viewer_config = {
    "ui": {
        "title": "HACHI Demo: Flu Detection",
        "encounter_display_name": "Patient",
        "column_display_names": {
            "patient_id": "Patient ID",
            "y": "Flu Outcome"
        }
    },
    "dataset": {
        "id_column": "patient_id",
        "note_column": "sentence",
        "summary_column": "llm_output",
        "metadata_columns": ["y"]
    },
    "prompts": {
        "prompts_directory": str(project_root / "notebooks" / "prompts"),
        "step1_summary": ["flu_keyphrases.txt"],
        "step2_extraction": ["concept_questions.txt"],
        "step3_initialization": ["baseline_init.txt"],
        "step4_generation": ["bayesian_iter.txt"]
    }
}

config_path = output_dir / "viewer_config.json"
with open(config_path, "w") as f:
    json.dump(viewer_config, f, indent=2)

print(f"Viewer config saved to: {config_path}")

In [ ]:
# Print the commands to run for generating the viewer
print("Run these commands from the project root directory:")
print()
print("# 1. Export data for the viewer")
print(f"python ui/export_standalone.py export \\")
print(f"    --llm-summaries {output_dir / 'keyphrases.csv'} \\")
print(f"    --initializations init_seed_1:{output_dir / 'ensemble' / 'init_seed_1'} \\")
print(f"    --config {output_dir / 'viewer_config.json'} \\")
print(f"    --output-dir {output_dir / 'viewer'}")
print()
print("# 2. Build the standalone HTML viewer")
print(f"python ui/build_standalone.py --output {output_dir / 'viewer' / 'viewer.html'}")
print()
print("# 3. Open the viewer in your browser and load:")
print(f"#    - {output_dir / 'viewer' / 'data.csv'}")
print(f"#    - {output_dir / 'viewer' / 'config.json'}")

---

# Summary

This demo showed the three main steps of HACHI:

1. **Keyphrase Extraction**: Used an LLM to extract clinically relevant terms from patient notes
2. **Ensemble Training**: Trained concept bottleneck models that learn interpretable yes/no concepts
3. **Result Review**: Exported results to an interactive HTML viewer

## Next Steps

To use HACHI on your own data:

1. Prepare a CSV with clinical notes and outcomes
2. Create custom prompts for your clinical domain
3. Run the pipeline with appropriate parameters
4. Review results and iterate with clinical expert feedback

See the [README](../README.md) for detailed usage instructions and the `exp_aki/` directory for a real-world example.