# HACHI Demo: Human-AI Co-design for Clinical Prediction Models

This notebook demonstrates the HACHI framework using a simple clinical scenario: **Flu Detection** from patient notes.

## What You'll Learn

1. **Step 1**: Extract keyphrases from clinical notes using an LLM
2. **Step 2**: Train an ensemble of concept bottleneck models
3. **Step 3**: Review results in an interactive HTML viewer

## Prerequisites
Set up your virtual environment and install the python packages in `requirements.txt`.

You need an API key from one of these providers:
- **OpenAI**: Get your key at https://platform.openai.com/api-keys
- **Anthropic (Claude)**: Get your key at https://console.anthropic.com/

## Estimated Cost

This demo uses a small dataset (40 samples) and minimal training to keep costs low:
- ~$0.50-2.00 with GPT-4o-mini
- ~$1.00-3.00 with Claude Haiku

## Setup

First, configure your API key. Create a `.env` file in the project root or set it directly below.

In [1]:
import os
import sys
from pathlib import Path

# Fix for Jupyter's event loop (allows nested asyncio.run() calls)
import nest_asyncio
nest_asyncio.apply()

# Add project root to path (parent of notebooks/)
notebook_dir = Path.cwd()
if notebook_dir.name == "notebooks":
    project_root = notebook_dir.parent
else:
    project_root = notebook_dir
sys.path.insert(0, str(project_root))

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
# ============================================
# CONFIGURE YOUR API KEY HERE
# ============================================
# Option 1: Set directly (not recommended for shared notebooks)
# os.environ["OPENAI_API_KEY"] = "sk-..."
# os.environ["ANTHROPIC_API_KEY"] = "sk-ant-..."

# Option 2: Create a .env file in the project root with:
# OPENAI_API_KEY=sk-...
# or
# ANTHROPIC_API_KEY=sk-ant-...

# Verify API key is set
if os.getenv("OPENAI_API_KEY"):
    print("OpenAI API key found")
    LLM_MODEL = "gpt-4o-mini"  # Cost-effective option
elif os.getenv("ANTHROPIC_API_KEY"):
    print("Anthropic API key found")
    LLM_MODEL = "claude-haiku-4-5-20251001"  # Cost-effective option
else:
    raise ValueError(
        "No API key found! Please set OPENAI_API_KEY or ANTHROPIC_API_KEY\n"
        "Either in your .env file or by uncommenting the lines above."
    )

print(f"Using model: {LLM_MODEL}")

OpenAI API key found
Using model: gpt-4o-mini

## Load the Demo Dataset

Our demo dataset contains 40 synthetic patient notes for flu detection (y=1: flu, y=0: no flu).

In [26]:
import pandas as pd
import numpy as np

pd.set_option('display.max_colwidth', 200)

# Load the demo dataset
data_path = "data/demo_patients.csv"
df = pd.read_csv(data_path)

print(f"Dataset shape: {df.shape}")
print(f"=====Outcome distribution=======")
print(df['y'].value_counts())
print("=====Example patient record======")
print(df['sentence'].iloc[0])
print(df['sentence'].iloc[-1])

Dataset shape: (40, 3)
=====Outcome distribution=======
y
1    20
0    20
Name: count, dtype: int64
=====Example patient record======
54yo female. Reports high temperature, runny nose, fever of 101.5F, nasal congestion.
45yo male. Reports runny nose, fever of 101.5F, nasal congestion, dry cough.

In [21]:
# Create output directories
output_dir = Path("output")
output_dir.mkdir(exist_ok=True)

# Create train/test split indices
np.random.seed(42)
n_samples = len(df)
indices = np.arange(n_samples)
np.random.shuffle(indices)

# 90% train, 10% test
train_size = int(0.9 * n_samples)
train_indices = indices[:train_size]
test_indices = indices[train_size:]

# Save indices file
indices_df = pd.DataFrame({
    'idx': list(train_indices) + list(test_indices),
    'partition': ['train'] * len(train_indices) + ['test'] * len(test_indices)
})

print(f"Train samples: {len(train_indices)}")
print(f"Test samples: {len(test_indices)}")

Train samples: 36
Test samples: 4

---

# Step 1: Extract Keyphrases from Clinical Notes

The first step in HACHI is to extract relevant keyphrases from each clinical note using an LLM. These keyphrases will be used as input features for concept generation.

This step:
1. Sends each note to the LLM with a keyphrase extraction prompt
2. The LLM identifies clinically relevant terms and phrases
3. Results are cached to avoid repeated API calls

In [22]:
# Run keyphrase extraction
from src.keyphrase_config import KeyphraseConfig
from src.keyphrase import Keyphrase

# Configure extraction
extract_config = KeyphraseConfig(
    llm_model_type=LLM_MODEL,
    prompt_file="prompts/keyphrases.txt",
    cache_file=str(output_dir / "demo_cache.db"),
    seed=42,
    batch_size=10,
    num_new_tokens=500,
    prompt_placeholder="{note}",
    text_column="sentence",
    is_image=False,
    index_col=None,
    llm_outputs_file=str(output_dir / "keyphrases.csv"),
    log_file=str(output_dir / "log_extract.txt")
)

print("Starting keyphrase extraction...")
print(f"This will process {len(train_indices)} training samples.")

# Run extraction
extractor = Keyphrase(extract_config)
result_df = extractor.extract(df, train_indices)

print(f"\nExtraction complete!")
print(f"Non-empty outputs: {(result_df.llm_output != '').sum()}")

Starting keyphrase extraction...
This will process 36 training samples.
DATASET LEN 36

  0%|          | 0/4 [00:00<?, ?it/s]

[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs][chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]

[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"31yo female. Reports r, e, q, u, e, s, t,  , f, o, r,  , l, a, b,  , w, o, r, k.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"58yo female. Reports b, l, o, o, d,  , p, r, e, s, s, u, r, e,  , c, h, e, c, k.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"56yo female. Reports a, n, n, u, a, l,  , p, h, y, s, i, c, a, l,  , e, x, a, m.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"45yo male. Reports runny nose, fever of 101.5F, nasal congestion, dry cough.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"67yo male. Reports m, e, d, i, c, a, t, i, o, n,  , r, e, f, i, l, l.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"55yo female. Reports s, k, i, n,  , r, a, s, h,  , o, n,  , a, r, m.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"58yo female. Reports dry cough, runny nose, high temperature, nasal congestion.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"56yo female. Reports b, l, o, o, d,  , p, r, e, s, s, u, r, e,  , c, h, e, c, k.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"27yo female. Reports b, l, o, o, d,  , p, r, e, s, s, u, r, e,  , c, h, e, c, k.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"57yo male. Reports b, l, o, o, d,  , p, r, e, s, s, u, r, e,  , c, h, e, c, k.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [1.45s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "{\"reasoning\":\"The patient note indicates symptoms and findings that are relevant to flu diagnosis. The presence of fever and dry cough are common flu symptoms, while body aches are also frequently reported by flu patients. These factors are included as they are strong indicators of flu risk.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"body aches, malaise\"]}",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "{\"reasoning\":\"The patient note indicates symptoms and findings that are relevant to flu diagnosis. The presence of fever and dry cough are common flu symptoms, while body aches are also frequently reported by flu patients. These factors are included as they are strong indicators of flu risk.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"body aches, malaise\"]}",
            "additional_kwargs": {
              "parsed": {
                "lc": 1,
                "type": "not_implemented",
                "id": [
                  "src",
                  "llm_response_types",
                  "ProtoConceptExtract"
                ],
                "repr": "ProtoConceptExtract(reasoning='The patient note indicates symptoms and findings that are relevant to flu diagnosis. The presence of fever and dry cough are common flu symptoms, while body aches are also frequently reported by flu patients. These factors are included as they are strong indicators of flu risk.', keyphrases=['fever, high temperature', 'dry cough, cough', 'body aches, malaise'])"
              },
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 76,
                "prompt_tokens": 355,
                "total_tokens": 431,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_name": "gpt-4o-mini-2024-07-18",
              "system_fingerprint": "fp_6e3c3ac586",
              "id": "chatcmpl-DpaXDshWhKB5qmLlWGHH01rzSDI2J",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run--3b0fc786-a8e1-4b87-8aa1-ecd10f0ef124-0",
            "usage_metadata": {
              "input_tokens": 355,
              "output_tokens": 76,
              "total_tokens": 431,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 76,
      "prompt_tokens": 355,
      "total_tokens": 431,
      "completion_tokens_details": {
        "accepted_prediction_tokens": 0,
        "audio_tokens": 0,
        "reasoning_tokens": 0,
        "rejected_prediction_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": 0,
        "cached_tokens": 0
      }
    },
    "model_name": "gpt-4o-mini-2024-07-18",
    "system_fingerprint": "fp_6e3c3ac586",
    "id": "chatcmpl-DpaXDshWhKB5qmLlWGHH01rzSDI2J",
    "service_tier": "default"
  },
  "run": null,
  "type": "LLMResult"
}
[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [1.51s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "{\"reasoning\":\"The patient note indicates symptoms and findings that are relevant to flu diagnosis. The presence of fever and dry cough are common flu symptoms, while body aches are also frequently reported by flu patients. These factors are included as they are strong indicators of flu risk.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"body aches, malaise\"]}",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "{\"reasoning\":\"The patient note indicates symptoms and findings that are relevant to flu diagnosis. The presence of fever and dry cough are common flu symptoms, while body aches are also frequently reported by flu patients. These factors are included as they are strong indicators of flu risk.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"body aches, malaise\"]}",
            "additional_kwargs": {
              "parsed": {
                "lc": 1,
                "type": "not_implemented",
                "id": [
                  "src",
                  "llm_response_types",
                  "ProtoConceptExtract"
                ],
                "repr": "ProtoConceptExtract(reasoning='The patient note indicates symptoms and findings that are relevant to flu diagnosis. The presence of fever and dry cough are common flu symptoms, while body aches are also frequently reported by flu patients. These factors are included as they are strong indicators of flu risk.', keyphrases=['fever, high temperature', 'dry cough, cough', 'body aches, malaise'])"
              },
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 76,
                "prompt_tokens": 355,
                "total_tokens": 431,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_name": "gpt-4o-mini-2024-07-18",
              "system_fingerprint": "fp_6e3c3ac586",
              "id": "chatcmpl-DpaXDWEhAHd6voPQgTE3h7yHGra1l",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run--45497735-1f56-4a0c-81a7-80837b4dddf6-0",
            "usage_metadata": {
              "input_tokens": 355,
              "output_tokens": 76,
              "total_tokens": 431,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 76,
      "prompt_tokens": 355,
      "total_tokens": 431,
      "completion_tokens_details": {

 25%|██▌       | 1/4 [00:02<00:07,  2.61s/it]

[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [2.47s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "{\"reasoning\":\"The patient note indicates symptoms and findings that can be associated with flu. The presence of fever is a common symptom of flu, while a dry cough and body aches are also typical indicators. These symptoms are considered positive risk factors for flu. The note does not mention any negative risk factors or exam findings, so the focus is solely on the positive indicators.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"body aches, malaise\"]}",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "{\"reasoning\":\"The patient note indicates symptoms and findings that can be associated with flu. The presence of fever is a common symptom of flu, while a dry cough and body aches are also typical indicators. These symptoms are considered positive risk factors for flu. The note does not mention any negative risk factors or exam findings, so the focus is solely on the positive indicators.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"body aches, malaise\"]}",
            "additional_kwargs": {
              "parsed": {
                "lc": 1,
                "type": "not_implemented",
                "id": [
                  "src",
                  "llm_response_types",
                  "ProtoConceptExtract"
                ],
                "repr": "ProtoConceptExtract(reasoning='The patient note indicates symptoms and findings that can be associated with flu. The presence of fever is a common symptom of flu, while a dry cough and body aches are also typical indicators. These symptoms are considered positive risk factors for flu. The note does not mention any negative risk factors or exam findings, so the focus is solely on the positive indicators.', keyphrases=['fever, high temperature', 'dry cough, cough', 'body aches, malaise'])"
              },
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 96,
                "prompt_tokens": 347,
                "total_tokens": 443,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_name": "gpt-4o-mini-2024-07-18",
              "system_fingerprint": "fp_6e3c3ac586",
              "id": "chatcmpl-DpaXElWydpk0mZ6OdenoYee4MlFNk",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run--451df71b-81a5-4a0c-aae9-18287016ea9f-0",
            "usage_metadata": {
              "input_tokens": 347,
              "output_tokens": 96,
              "total_tokens": 443,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 96,
      "prompt_tokens": 347,
      "total_tokens": 443,
      "completion_tokens_details": {
        "accepted_prediction_tokens": 0,
        "audio_tokens": 0,
        "reasoning_tokens": 0,
        "rejected_prediction_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": 0,
        "cached_tokens": 0
      }
    },
    "model_name": "gpt-4o-mini-2024-07-18",
    "system_fingerprint": "fp_6e3c3ac586",
    "id": "chatcmpl-DpaXElWydpk0mZ6OdenoYee4MlFNk",
    "service_tier": "default"
  },
  "run": null,
  "type": "LLMResult"
}
[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [2.57s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "{\"reasoning\":\"The patient note indicates symptoms and findings that can be associated with flu. The presence of fever is a common symptom of flu, hence it is included as a positive risk factor. A dry cough is also a typical symptom of flu, making it another positive risk factor. Body aches are frequently reported by patients with flu, thus included as well. These symptoms are all related to the flu and are commonly recognized in clinical settings.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"body aches, malaise\"]}",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "{\"reasoning\":\"The patient note indicates symptoms and findings that can be associated with flu. The presence of fever is a common symptom of flu, hence it is included as a positive risk factor. A dry cough is also a typical symptom of flu, making it another positive risk factor. Body aches are frequently reported by patients with flu, thus included as well. These symptoms are all related to the flu and are commonly recognized in clinical settings.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"body aches, malaise\"]}",
            "additional_kwargs": {
              "parsed": {
                "lc": 1,
                "type": "not_implemented",
                "id": [
                  "src",
                  "llm_response_types",
                  "ProtoConceptExtract"
                ],
                "repr": "ProtoConceptExtract(reasoning='The patient note indicates symptoms and findings that can be associated with flu. The presence of fever is a common symptom of flu, hence it is included as a positive risk factor. A dry cough is also a typical symptom of flu, making it another positive risk factor. Body aches are frequently reported by patients with flu, thus included as well. These symptoms are all related to the flu and are commonly recognized in clinical settings.', keyphrases=['fever, high temperature', 'dry cough, cough', 'body aches, malaise'])"
              },
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 110,
                "prompt_tokens": 355,
                "total_tokens": 465,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_name": "gpt-4o-mini-2024-07-18",
              "system_fingerprint": "fp_6e3c3ac586",
              "id": "chatcmpl-DpaXDDfFAR4gTmBOxWQ05GTw3JaZL",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run--b5fca7e6-bd33-472b-a073-7025fab2b71a-0",
            "usage_metadata": {
              "input_tokens": 355,
              "output_tokens": 110,
              "total_tokens": 465,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 110,
      "prompt_tokens": 355,
      "total_tokens": 465,
      "completion_tokens_details": {
        "accepted_prediction_tokens": 0,
        "audio_tokens": 0,
        "reasoning_tokens": 0,
        "rejected_prediction_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": 0,
        "cached_tokens": 0
      }
    },
    "model_name": "gpt-4o-mini-2024-07-18",
    "system_fingerprint": "fp_6e3c3ac586",
    "id": "chatcmpl-DpaXDDfFAR4gTmBOxWQ05GTw3JaZL",
    "service_tier": "default"
  },
  "run": null,
  "type": "LLMResult"
}
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [6ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [5ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [6ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [6ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [5ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [5ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [5ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [5ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [6ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [6ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.59s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.59s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.59s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.59s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.59s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.59s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.59s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.59s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.59s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.59s] Exiting Chain run with output:
[outputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"68yo male. Reports fever of 101.5F, nasal congestion, high temperature, wet cough, dry cough.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"54yo female. Reports high temperature, runny nose, fever of 101.5F, nasal congestion.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"75yo male. Reports dry cough, fever of 101.5F, nasal congestion, wet cough.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"39yo female. Reports high temperature, runny nose, fever of 101.5F, wet cough.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"36yo male. Reports wet cough, dry cough, high temperature, fever of 101.5F, runny nose.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"40yo female. Reports runny nose, wet cough, nasal congestion.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [

 50%|█████     | 2/4 [00:05<00:05,  2.71s/it]

[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [2.75s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "{\"reasoning\":\"The patient is a 75-year-old male who reports several symptoms. The presence of a fever (101.5F) is a positive risk factor for flu, as it indicates an infection. The dry cough is also a symptom associated with flu, making it another positive risk factor. Nasal congestion can be a symptom of flu, but it is less specific than fever and cough. The wet cough may indicate a secondary infection or complication, but it is still relevant as a symptom. Therefore, the keyphrases focus on the significant symptoms that are indicative of flu.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"nasal congestion, stuffy nose\",\"wet cough, productive cough\",\"body aches, malaise\"]}",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "{\"reasoning\":\"The patient is a 75-year-old male who reports several symptoms. The presence of a fever (101.5F) is a positive risk factor for flu, as it indicates an infection. The dry cough is also a symptom associated with flu, making it another positive risk factor. Nasal congestion can be a symptom of flu, but it is less specific than fever and cough. The wet cough may indicate a secondary infection or complication, but it is still relevant as a symptom. Therefore, the keyphrases focus on the significant symptoms that are indicative of flu.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"nasal congestion, stuffy nose\",\"wet cough, productive cough\",\"body aches, malaise\"]}",
            "additional_kwargs": {
              "parsed": {
                "lc": 1,
                "type": "not_implemented",
                "id": [
                  "src",
                  "llm_response_types",
                  "ProtoConceptExtract"
                ],
                "repr": "ProtoConceptExtract(reasoning='The patient is a 75-year-old male who reports several symptoms. The presence of a fever (101.5F) is a positive risk factor for flu, as it indicates an infection. The dry cough is also a symptom associated with flu, making it another positive risk factor. Nasal congestion can be a symptom of flu, but it is less specific than fever and cough. The wet cough may indicate a secondary infection or complication, but it is still relevant as a symptom. Therefore, the keyphrases focus on the significant symptoms that are indicative of flu.', keyphrases=['fever, high temperature', 'dry cough, cough', 'nasal congestion, stuffy nose', 'wet cough, productive cough', 'body aches, malaise'])"
              },
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 154,
                "prompt_tokens": 332,
                "total_tokens": 486,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_name": "gpt-4o-mini-2024-07-18",
              "system_fingerprint": "fp_6e3c3ac586",
              "id": "chatcmpl-DpaXGtmnLezWmoG0SExB9ur9IPrqb",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run--f77a417c-119b-47d5-be8d-4b9ce26cb3d9-0",
            "usage_metadata": {
              "input_tokens": 332,
              "output_tokens": 154,
              "total_tokens": 486,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 154,
      "prompt_tokens": 332,
      "total_tokens": 486,
      "completion_tokens_details": {
        "accepted_prediction_tokens": 0,
        "audio_tokens": 0,
        "reasoning_tokens": 0,
        "rejected_prediction_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": 0,
        "cached_tokens": 0
      }
    },
    "model_name": "gpt-4o-mini-2024-07-18",
    "system_fingerprint": "fp_6e3c3ac586",
    "id": "chatcmpl-DpaXGtmnLezWmoG0SExB9ur9IPrqb",
    "service_tier": "default"
  },
  "run": null,
  "type": "LLMResult"
}
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [5ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [5ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [6ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [5ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [5ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [6ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [6ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [7ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [6ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [7ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.77s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.77s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.77s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.77s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.77s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.77s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.77s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.77s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.77s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.77s] Exiting Chain run with output:
[outputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"61yo male. Reports wet cough, nasal congestion, fever of 101.5F, runny nose.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"50yo female. Reports m, e, d, i, c, a, t, i, o, n,  , r, e, f, i, l, l.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"58yo female. Reports k, n, e, e,  , p, a, i, n,  , a, f, t, e, r,  , e, x, e, r, c, i, s, e.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"38yo male. Reports runny nose, fever of 101.5F, high temperature, nasal congestion, dry cough.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"48yo female. Reports k, n, e, e,  , p, a, i, n,  , a, f, t, e, r,  , e, x, e, r, c, i, s, e.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"51yo male. Reports b, l, o, o, d,  , p, r, e, s, s, u, r, e,  , c, h, e, c, k.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"31yo male. Reports runny nose, dry cough, nasal congestion, wet cough.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"49yo female. Reports dry cough, nasal congestion, wet cough.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"48yo female. Reports r, o, u, t, i, n, e,  , f, o, l, l, o, w, -, u, p,  , v, i, s, i, t.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [

 75%|███████▌  | 3/4 [00:08<00:02,  2.95s/it]

[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [3.22s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "{\"reasoning\":\"The patient note indicates symptoms and findings that are relevant to flu diagnosis. The presence of fever is a common symptom associated with flu, making it a positive risk factor. A dry cough is also a typical symptom of flu, contributing to the risk. Body aches are frequently reported in flu cases, indicating a positive risk factor as well. These factors are all related to the flu and help in predicting the likelihood of the patient having it.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"body aches, malaise\"]}",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "{\"reasoning\":\"The patient note indicates symptoms and findings that are relevant to flu diagnosis. The presence of fever is a common symptom associated with flu, making it a positive risk factor. A dry cough is also a typical symptom of flu, contributing to the risk. Body aches are frequently reported in flu cases, indicating a positive risk factor as well. These factors are all related to the flu and help in predicting the likelihood of the patient having it.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"body aches, malaise\"]}",
            "additional_kwargs": {
              "parsed": {
                "lc": 1,
                "type": "not_implemented",
                "id": [
                  "src",
                  "llm_response_types",
                  "ProtoConceptExtract"
                ],
                "repr": "ProtoConceptExtract(reasoning='The patient note indicates symptoms and findings that are relevant to flu diagnosis. The presence of fever is a common symptom associated with flu, making it a positive risk factor. A dry cough is also a typical symptom of flu, contributing to the risk. Body aches are frequently reported in flu cases, indicating a positive risk factor as well. These factors are all related to the flu and help in predicting the likelihood of the patient having it.', keyphrases=['fever, high temperature', 'dry cough, cough', 'body aches, malaise'])"
              },
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 112,
                "prompt_tokens": 349,
                "total_tokens": 461,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_name": "gpt-4o-mini-2024-07-18",
              "system_fingerprint": "fp_6e3c3ac586",
              "id": "chatcmpl-DpaXJZl2gjJvK7OPiQ3KavkfVkRLi",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run--6cef9d0c-2894-4294-814a-b25d8bb68543-0",
            "usage_metadata": {
              "input_tokens": 349,
              "output_tokens": 112,
              "total_tokens": 461,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 112,
      "prompt_tokens": 349,
      "total_tokens": 461,
      "completion_tokens_details": {
        "accepted_prediction_tokens": 0,
        "audio_tokens": 0,
        "reasoning_tokens": 0,
        "rejected_prediction_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": 0,
        "cached_tokens": 0
      }
    },
    "model_name": "gpt-4o-mini-2024-07-18",
    "system_fingerprint": "fp_6e3c3ac586",
    "id": "chatcmpl-DpaXJZl2gjJvK7OPiQ3KavkfVkRLi",
    "service_tier": "default"
  },
  "run": null,
  "type": "LLMResult"
}[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [3.21s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "{\"reasoning\":\"The patient is a 40-year-old male who reports several symptoms. The presence of fever (101.5F) is a positive risk factor for flu, as it indicates an infection. The report of nasal congestion and wet cough suggests respiratory involvement, which is also common in flu cases. The dry cough mentioned is another symptom that can be associated with flu, although it can also indicate other conditions. Therefore, I included fever, dry cough, and body aches as keyphrases, as they are relevant to flu diagnosis.\",\"keyphrases\":[\"fever, high temperature\",\"wet cough, productive cough\",\"dry cough, cough\",\"nasal congestion, stuffy nose\",\"body aches, malaise\"]}",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "{\"reasoning\":\"The patient is a 40-year-old male who reports several symptoms. The presence of fever (101.5F) is a positive risk factor for flu, as it indicates an infection. The report of nasal congestion and wet cough suggests respiratory involvement, which is also common in flu cases. The dry cough mentioned is another symptom that can be associated with flu, although it can also indicate other conditions. Therefore, I included fever, dry cough, and body aches as keyphrases, as they are relevant to flu diagnosis.\",\"keyphrases\":[\"fever, high temperature\",\"wet cough, productive cough\",\"dry cough, cough\",\"nasal congestion, stuffy nose\",\"body aches, malaise\"]}",
            "additional_kwargs": {
              "parsed": {
                "lc": 1,
                "type": "not_implemented",
                "id": [
                  "src",
                  "llm_response_types",
                  "ProtoConceptExtract"
                ],
                "repr": "ProtoConceptExtract(reasoning='The patient is a 40-year-old male who reports several symptoms. The presence of fever (101.5F) is a positive risk factor for flu, as it indicates an infection. The report of nasal congestion and wet cough suggests respiratory involvement, which is also common in flu cases. The dry cough mentioned is another symptom that can be associated with flu, although it can also indicate other conditions. Therefore, I included fever, dry cough, and body aches as keyphrases, as they are relevant to flu diagnosis.', keyphrases=['fever, high temperature', 'wet cough, productive cough', 'dry cough, cough', 'nasal congestion, stuffy nose', 'body aches, malaise'])"
              },
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 145,
                "prompt_tokens": 332,
                "total_tokens": 477,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_name": "gpt-4o-mini-2024-07-18",
              "system_fingerprint": "fp_6e3c3ac586",
              "id": "chatcmpl-DpaXJFZgKanrUUTtGyPLRSTHcOnDZ",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run--45e0a055-4ad2-4885-a171-011147e4b6c4-0",
            "usage_metadata": {
              "input_tokens": 332,
              "output_tokens": 145,
              "total_tokens": 477,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 145,
      "prompt_tokens": 332,
      "total_tokens": 477,
      "completion_tokens_details": {
        "accepted_prediction_tokens": 0,
        "audio_tokens": 0,
        "reasoning_tokens": 0,
        "rejected_prediction_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": 0,
        "cached_tokens": 0
      }
    },
    "model_name": "gpt-4o-mini-2024-07-18",
    "system_fingerprint": "fp_6e3c3ac586",
    "id": "chatcmpl-DpaXJFZgKanrUUTtGyPLRSTHcOnDZ",
    "service_tier": "default"
  },
  "run": null,
  "type": "LLMResult"
}

[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [3.22s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "{\"reasoning\":\"The patient presents with several symptoms that are indicative of a flu infection. The fever of 101.5F is a positive risk factor for flu, as elevated body temperature is commonly associated with viral infections. The wet cough and runny nose are also symptoms that can be associated with flu, making them positive risk factors. Nasal congestion is another symptom that aligns with flu presentations. Each of these symptoms can be categorized into primary descriptors, synonyms, and broader generalizations.\",\"keyphrases\":[\"fever, high temperature\",\"wet cough, productive cough\",\"nasal congestion, stuffy nose\",\"runny nose, rhinorrhea\",\"body aches, malaise\"]}",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "{\"reasoning\":\"The patient presents with several symptoms that are indicative of a flu infection. The fever of 101.5F is a positive risk factor for flu, as elevated body temperature is commonly associated with viral infections. The wet cough and runny nose are also symptoms that can be associated with flu, making them positive risk factors. Nasal congestion is another symptom that aligns with flu presentations. Each of these symptoms can be categorized into primary descriptors, synonyms, and broader generalizations.\",\"keyphrases\":[\"fever, high temperature\",\"wet cough, productive cough\",\"nasal congestion, stuffy nose\",\"runny nose, rhinorrhea\",\"body aches, malaise\"]}",
            "additional_kwargs": {
              "parsed": {
                "lc": 1,
                "type": "not_implemented",
                "id": [
                  "src",
                  "llm_response_types",
                  "ProtoConceptExtract"
                ],
                "repr": "ProtoConceptExtract(reasoning='The patient presents with several symptoms that are indicative of a flu infection. The fever of 101.5F is a positive risk factor for flu, as elevated body temperature is commonly associated with viral infections. The wet cough and runny nose are also symptoms that can be associated with flu, making them positive risk factors. Nasal congestion is another symptom that aligns with flu presentations. Each of these symptoms can be categorized into primary descriptors, synonyms, and broader generalizations.', keyphrases=['fever, high temperature', 'wet cough, productive cough', 'nasal congestion, stuffy nose', 'runny nose, rhinorrhea', 'body aches, malaise'])"
              },
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 137,
                "prompt_tokens": 333,
                "total_tokens": 470,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_name": "gpt-4o-mini-2024-07-18",
              "system_fingerprint": "fp_6e3c3ac586",
              "id": "chatcmpl-DpaXJ7GBSarX9bzqKSiaOnSTloUsw",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run--57ae51bb-8304-4902-889c-4de787f36bf7-0",
            "usage_metadata": {
              "input_tokens": 333,
              "output_tokens": 137,
              "total_tokens": 470,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 137,
      "prompt_tokens": 333,
      "total_tokens": 470,
      "completion_tokens_details": {
        "accepted_prediction_tokens": 0,
        "audio_tokens": 0,
        "reasoning_tokens": 0,
        "rejected_prediction_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": 0,
        "cached_tokens": 0
      }
    },
    "model_name": "gpt-4o-mini-2024-07-18",
    "system_fingerprint": "fp_6e3c3ac586",
    "id": "chatcmpl-DpaXJ7GBSarX9bzqKSiaOnSTloUsw",
    "service_tier": "default"
  },
  "run": null,
  "type": "LLMResult"
}
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [3ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [2ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [3ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [3ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [2ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [3ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [2ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [3ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [3ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [3ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [3.23s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [3.23s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [3.23s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [3.23s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [3.22s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [3.22s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [3.23s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [3.23s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [3.23s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [3.23s] Exiting Chain run with output:
[outputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You are extracting clinical factors from patient notes for predicting whether or not they have the flu.\n\nExtract factors related to:\n- Patient symptoms that are negative or positive risk factors\n- Exam findings that are negative or positive risk factors\n\nFor each factor, provide the primary descriptor and synonyms. That is:\n1. The primary descriptor (exact or paraphrased from the note). Each descriptor should be 1-2 words.\n2. Synonyms or alternative phrasings. Separate items with commas\n3. Broader generalizations that capture similar concepts. Separate items with commas\n\nYou MUST output at least one set of keyphrases for each patient. Aim for 3-5 keyphrases per patient.\n\nNote:\n\"36yo male. Reports r, e, q, u, e, s, t,  , f, o, r,  , l, a, b,  , w, o, r, k.\"\n\nOutput Format:\n{\n  \"reasoning\": \"Step-by-step reasoning through the note\",\n  \"keyphrases\": [\n    \"fever, high temperature\",\n    \"dry cough, cough\",\n    \"body aches, malaise\"]\n}"
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [

100%|██████████| 4/4 [00:11<00:00,  2.81s/it]

[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [2.61s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "{\"reasoning\":\"The patient note indicates symptoms and findings that are relevant to flu diagnosis. The presence of fever and dry cough are common flu symptoms, while body aches are also frequently reported by flu patients. These factors are included as they are strong indicators of flu risk.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"body aches, malaise\"]}",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "{\"reasoning\":\"The patient note indicates symptoms and findings that are relevant to flu diagnosis. The presence of fever and dry cough are common flu symptoms, while body aches are also frequently reported by flu patients. These factors are included as they are strong indicators of flu risk.\",\"keyphrases\":[\"fever, high temperature\",\"dry cough, cough\",\"body aches, malaise\"]}",
            "additional_kwargs": {
              "parsed": {
                "lc": 1,
                "type": "not_implemented",
                "id": [
                  "src",
                  "llm_response_types",
                  "ProtoConceptExtract"
                ],
                "repr": "ProtoConceptExtract(reasoning='The patient note indicates symptoms and findings that are relevant to flu diagnosis. The presence of fever and dry cough are common flu symptoms, while body aches are also frequently reported by flu patients. These factors are included as they are strong indicators of flu risk.', keyphrases=['fever, high temperature', 'dry cough, cough', 'body aches, malaise'])"
              },
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 76,
                "prompt_tokens": 355,
                "total_tokens": 431,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_name": "gpt-4o-mini-2024-07-18",
              "system_fingerprint": "fp_6e3c3ac586",
              "id": "chatcmpl-DpaXN4Qe8CI5ZkXTZCZdPDN790nRk",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run--9420208a-16a4-47da-8a77-9f76ff7ba352-0",
            "usage_metadata": {
              "input_tokens": 355,
              "output_tokens": 76,
              "total_tokens": 431,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 76,
      "prompt_tokens": 355,
      "total_tokens": 431,
      "completion_tokens_details": {
        "accepted_prediction_tokens": 0,
        "audio_tokens": 0,
        "reasoning_tokens": 0,
        "rejected_prediction_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": 0,
        "cached_tokens": 0
      }
    },
    "model_name": "gpt-4o-mini-2024-07-18",
    "system_fingerprint": "fp_6e3c3ac586",
    "id": "chatcmpl-DpaXN4Qe8CI5ZkXTZCZdPDN790nRk",
    "service_tier": "default"
  },
  "run": null,
  "type": "LLMResult"
}
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [3ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [4ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [4ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [3ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [3ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [3ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.62s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.62s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.62s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.62s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.62s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [2.62s] Exiting Chain run with output:
[outputs]
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'runny nose, rhinorrhea', 'nasal congestion, stuffy nose', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'runny nose, rhinorrhea', 'nasal congestion, stuffy nose', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'wet cough, productive cough', 'nasal congestion, stuffy nose', 'respiratory symptoms, upper respiratory tract symptoms']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'runny nose, nasal discharge', 'wet cough, productive cough']
['runny nose, rhinorrhea', 'wet cough, productive cough', 'nasal congestion, stuffy nose']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'wet cough, productive cough', 'nasal congestion, stuffy nose', 'body aches, malaise']
['fever, high temperature', 'runny nose, nasal discharge', 'nasal congestion, stuffy nose']
['fever, high temperature', 'dry cough, cough', 'nasal congestion, stuffy nose', 'wet cough, productive cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'wet cough, productive cough', 'dry cough, cough', 'nasal congestion, stuffy nose', 'body aches, malaise']
['dry cough, cough', 'nasal congestion, stuffy nose', 'wet cough, productive cough']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'wet cough, productive cough', 'nasal congestion, stuffy nose', 'runny nose, rhinorrhea', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'runny nose, nasal congestion', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['runny nose, rhinorrhea', 'dry cough, nonproductive cough', 'nasal congestion, stuffy nose', 'wet cough, productive cough']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'nasal congestion, stuffy nose', 'wet cough, productive cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']
['fever, high temperature', 'dry cough, cough', 'runny nose, nasal congestion', 'respiratory symptoms, upper respiratory infection', 'viral infection, flu-like symptoms']
['fever, high temperature', 'dry cough, cough', 'body aches, malaise']

Extraction complete!
Non-empty outputs: 36

In [23]:
# View sample extractions
result_df[result_df.llm_output != ""].head()

,index,patient_id,sentence,y,llm_output
0,0,FLU-009,"54yo female. Reports high temperature, runny nose, fever of 101.5F, nasal congestion.",1,"fever, high temperature,runny nose, nasal discharge,nasal congestion, stuffy nose"
1,1,FLU-003,"40yo male. Reports nasal congestion, wet cough, fever of 101.5F, dry cough.",1,"fever, high temperature,wet cough, productive cough,dry cough, cough,nasal congestion, stuffy nose,body aches, malaise"
2,2,FLU-010,"61yo male. Reports wet cough, nasal congestion, fever of 101.5F, runny nose.",1,"fever, high temperature,wet cough, productive cough,nasal congestion, stuffy nose,runny nose, rhinorrhea,body aches, malaise"
3,3,CTRL-016,"48yo female. Reports k, n, e, e, , p, a, i, n, , a, f, t, e, r, , e, x, e, r, c, i, s, e.",0,"fever, high temperature,dry cough, cough,body aches, malaise"
4,4,CTRL-005,"55yo female. Reports s, k, i, n, , r, a, s, h, , o, n, , a, r, m.",0,"fever, high temperature,dry cough, cough,body aches, malaise"

---

# Step 2: Train the Ensemble

Now we train an ensemble of concept bottleneck models using the `EnsembleTrainer` class.

The training process:
1. **Baseline initialization**: Generate initial concept candidates from the keyphrases
2. **Iterative refinement**: Add/refine concepts based on model residuals

We use minimal settings to keep API costs low:
- 1 initialization seed
- 1 epoch
- 3 target concepts

This is similar to running `lm()` in R, but for unstructured text data!

In [10]:
# Configure the ensemble trainer
from src.ensemble_trainer import (
    EnsembleTrainer,
    EnsembleConfig,
    ModelConfig,
    LLMConfig,
    DataConfig,
    TrainingConfig,
    ConceptConfig,
)

# Create configuration (similar to specifying a model formula in R)
ensemble_config = EnsembleConfig(
    init_seeds=[1],  # Single seed for demo (use multiple for production)
    model=ModelConfig(
        residual_model_type="l2",
        final_model_type="l1_sklearn",
        cv=3,
    ),
    llm=LLMConfig(
        llm_model=LLM_MODEL,
        max_new_tokens=2000,
        cache_file=str(output_dir / "demo_cache.db"),
    ),
    data=DataConfig(
        text_summary_column="llm_output",
        concept_column="llm_output",
        max_section_length=5000,
    ),
    training=TrainingConfig(
        num_epochs=0,           # Minimal for demo
        num_greedy_epochs=0,
        batch_size=40,
        batch_concept_size=10,
        train_frac=0.5,
    ),
    concept=ConceptConfig(
        goal_num_meta_concepts=3,   # Target number of concepts
        max_meta_concepts=7,        # Max to consider
        num_top_residual_words=30,
        prompt_iter_file="prompts/bayesian_iter.txt",
        prompt_concepts_file="prompts/concept_questions.txt",
        baseline_init_file="prompts/baseline_init.txt",
    ),
)

print("Configuration created!")
print(f"  Model: {LLM_MODEL}")
print(f"  Target concepts: {ensemble_config.concept.goal_num_meta_concepts}")
print(f"  Training epochs: {ensemble_config.training.num_epochs}")

Configuration created!
  Model: gpt-4o-mini
  Target concepts: 3
  Training epochs: 0

In [11]:
# Load the data with keyphrases
train_df = result_df.iloc[train_indices]
train_df["sample_weight"] = 1
train_df

,index,patient_id,sentence,y,llm_output,sample_weight
19,19,CTRL-002,Chief complaint: blood pressure check\nHPI: 58yo female.\nExam: Pharynx clear. Temperature 98.6F.\nAssessment: No acute illness. Continue current management.,0,"normal temperature, no fever,clear pharynx, no throat redness,no acute illness, stable condition",1
16,16,CTRL-015,Chief complaint: request for lab work\nHPI: 31yo female.\nExam: Vital signs normal. Pharynx clear.\nAssessment: No acute illness. Continue current management.,0,"normal vital signs, stable vitals,clear pharynx, throat clear,no acute illness, no current illness",1
15,15,CTRL-014,Chief complaint: blood pressure check\nHPI: 57yo male.\nExam: No lymphadenopathy. Temperature 98.6F.\nAssessment: No acute illness. Continue current management.,0,"normal temperature, no fever,no acute illness, stable condition,no lymphadenopathy, no swollen glands",1
26,26,CTRL-019,Chief complaint: blood pressure check\nHPI: 27yo female.\nExam: Temperature 98.6F. Vital signs normal.\nAssessment: No acute illness. Continue current management.,0,"normal temperature, no fever,no cough, absence of cough,no body aches, absence of malaise",1
4,4,CTRL-005,Chief complaint: skin rash on arm\nHPI: 55yo female.\nExam: No lymphadenopathy. Pharynx clear.\nAssessment: No acute illness. Continue current management.,0,"skin rash, dermatitis,no acute illness, stable condition,clear pharynx, normal throat examination",1
12,12,CTRL-003,Chief complaint: blood pressure check\nHPI: 56yo female.\nExam: Vital signs normal. Pharynx clear.\nAssessment: No acute illness. Continue current management.,0,"no acute illness, absence of illness,normal vital signs, stable vital signs,clear pharynx, unobstructed throat",1
37,37,FLU-017,"Chief complaint: flu-like symptoms\nHPI: 58yo female. Reports fatigue and malaise, runny nose, body aches and myalgias, nasal congestion.\nExam: Temperature 101.2F. Mild tachycardia.\nAssessment: ...",1,"fever, high temperature,fatigue, tiredness,body aches, myalgias,runny nose, nasal discharge,mild tachycardia, increased heart rate",1
27,27,CTRL-013,Chief complaint: annual physical exam\nHPI: 56yo female.\nExam: Temperature 98.6F. Pharynx clear.\nAssessment: No acute illness. Continue current management.,0,"normal temperature, no fever,clear pharynx, no throat infection,no acute illness, stable condition",1
39,39,FLU-007,"Chief complaint: flu-like symptoms\nHPI: 45yo male. Reports nasal congestion, fever of 101.5F, runny nose, wet cough.\nExam: Temperature 101.2F. Cervical lymphadenopathy. Mild tachycardia.\nAssess...",1,"fever, high temperature,nasal congestion, stuffy nose,wet cough, productive cough,cervical lymphadenopathy, swollen lymph nodes,mild tachycardia, increased heart rate",1
6,6,CTRL-010,Chief complaint: medication refill\nHPI: 67yo male.\nExam: Vital signs normal. Pharynx clear.\nAssessment: No acute illness. Continue current management.,0,"no acute illness, absence of illness,normal vital signs, stable vitals,clear pharynx, no throat inflammation",1
25,25,FLU-016,"Chief complaint: flu-like symptoms\nHPI: 48yo female. Reports fatigue and malaise, dry cough, body aches and myalgias, nasal congestion.\nExam: Mild tachycardia. Cervical lymphadenopathy.\nAssessm...",1,"fatigue, tiredness,dry cough, cough,body aches, myalgias,mild tachycardia, increased heart rate,cervical lymphadenopathy, swollen lymph nodes",1
9,9,CTRL-012,Chief complaint: annual physical exam\nHPI: 46yo male.\nExam: Vital signs normal. Temperature 98.6F.\nAssessment: No acute illness. Continue current management.,0,"normal temperature, no fever,no acute illness, absence of symptoms,normal vital signs, stable condition",1
13,13,FLU-018,"Chief complaint: flu-like symptoms\nHPI: 36yo male. Reports dry cough, fatigue and malaise, body aches and myalgias, wet cough, runny nose.\nExam: Pharynx erythematous. Mild tachycardia. Cervical ...",1,"dry cough, cough,fatigue, tiredness,body aches, myalgias,erythematous pharynx, red throat,cervical lymphadenopathy, swollen lymph nodes",1
31,31,CTRL-007,Chief complaint: mild back pain\nHPI: 27yo male.\nExam: Pharynx clear. Temperature 98.6F.\nAssessment: No acute illness. Continue current management.,0,"normal temperature, 98.6F,clear pharynx, no throat redness,no acute illness, stable condition",1
34,34,FLU-008,"Chief complaint: flu-like symptoms\nHPI: 39yo female. Reports body aches and myalgias, runny nose, fever of 101.5F, wet cough.\nExam: Pharynx erythematous. Cervical lymphadenopathy.\nAssessment: I...",1,"fever, high temperature,body aches, myalgias, malaise,wet cough, productive cough,erythematous pharynx, red throat,cervical lymphadenopathy, swollen lymph nodes",1
8,8,FLU-004,"Chief complaint: flu-like symptoms\nHPI: 40yo female. Reports nasal congestion, dry cough, runny nose.\nExam: Temperature 101.2F. Mild tachycardia.\nAssessment: Influenza likely. Recommend rest, f...",1,"flu-like symptoms, influenza symptoms,nasal congestion, stuffy nose,dry cough, cough,fever, high temperature,mild tachycardia, increased heart rate",1
17,17,CTRL-006,Chief complaint: blood pressure check\nHPI: 47yo male.\nExam: Vital signs normal. Temperature 98.6F.\nAssessment: No acute illness. Continue current management.,0,"normal temperature, no fever,no acute illness, stable condition,normal vital signs, healthy status",1
24,24,FLU-019,"Chief complaint: flu-like symptoms\nHPI: 68yo male. Reports fever of 101.5F, wet cough, body aches and myalgias, dry cough, nasal congestion.\nExam: Pharynx erythematous. Cervical lymphadenopathy....",1,"fever, high temperature,wet cough, cough,body aches, myalgias,erythematous pharynx, red throat,cervical lymphadenopathy, swollen lymph nodes",1
0,0,FLU-009,"Chief complaint: flu-like symptoms\nHPI: 54yo female. Reports body aches and myalgias, runny nose, fever of 101.5F, fatigue and malaise.\nExam: Temperature 101.2F. Pharynx erythematous. Mild tachy...",1,"fever, high temperature,body aches, myalgias,runny nose, nasal congestion,fatigue, malaise,erythematous pharynx, red throat",1
33,33,FLU-006,"Chief complaint: flu-like symptoms\nHPI: 75yo male. Reports runny nose, fatigue and malaise, fever of 101.5F, wet cough.\nExam: Mild tachycardia. Cervical lymphadenopathy.\nAssessment: Influenza l...",1,"fever, high temperature,runny nose, nasal discharge,fatigue, tiredness,wet cough, productive cough,cervical lymphadenopathy, swollen lymph nodes",1
5,5,CTRL-004,Chief complaint: blood pressure check\nHPI: 51yo male.\nExam: Pharynx clear. Vital signs normal.\nAssessment: No acute illness. Continue current management.,0,"no acute illness, absence of illness,normal vital signs, stable vital signs,clear pharynx, unremarkable throat",1
11,11,CTRL-008,Chief complaint: knee pain after exercise\nHPI: 58yo female.\nExam: Temperature 98.6F. No lymphadenopathy.\nAssessment: No acute illness. Continue current management.,0,"normal temperature, 98.6F,no acute illness, stable condition,no lymphadenopathy, no swollen lymph nodes",1
1,1,FLU-003,"Chief complaint: flu-like symptoms\nHPI: 40yo male. Reports wet cough, dry cough, runny nose, fever of 101.5F.\nExam: Mild tachycardia. Pharynx erythematous.\nAssessment: Influenza likely. Recomme...",1,"flu-like symptoms, influenza symptoms,wet cough, productive cough,dry cough, non-productive cough,runny nose, rhinorrhea,fever, high temperature",1
29,29,FLU-000,"Chief complaint: flu-like symptoms\nHPI: 49yo female. Reports fatigue and malaise, wet cough, dry cough.\nExam: Cervical lymphadenopathy. Pharynx erythematous. Mild tachycardia.\nAssessment: Influ...",1,"flu-like symptoms, influenza symptoms,fatigue, tiredness, exhaustion,cough, respiratory symptoms,cervical lymphadenopathy, swollen lymph nodes,erythematous pharynx, red throat",1
21,21,CTRL-011,Chief complaint: routine follow-up visit\nHPI: 48yo female.\nExam: Vital signs normal. Temperature 98.6F.\nAssessment: No acute illness. Continue current management.,0,"normal temperature, no fever,no acute illness, stable condition,routine follow-up, regular check-up",1
2,2,FLU-010,"Chief complaint: flu-like symptoms\nHPI: 61yo male. Reports dry cough, wet cough, fever of 101.5F, body aches and myalgias.\nExam: Mild tachycardia. Pharynx erythematous. Temperature 101.2F.\nAsse...",1,"fever, high temperature,dry cough, cough,body aches, malaise,erythematous pharynx, red throat,tachycardia, increased heart rate",1
30,30,CTRL-018,Chief complaint: medication refill\nHPI: 50yo female.\nExam: Pharynx clear. No lymphadenopathy.\nAssessment: No acute illness. Continue current management.,0,"no acute illness, absence of illness,clear pharynx, normal throat,no lymphadenopathy, no swollen glands",1
36,36,FLU-015,"Chief complaint: flu-like symptoms\nHPI: 38yo male. Reports nasal congestion, fever of 101.5F, body aches and myalgias, wet cough, runny nose.\nExam: Pharynx erythematous. Cervical lymphadenopathy...",1,"fever, high temperature, elevated body temperature,wet cough, productive cough, cough with phlegm,body aches, myalgias, muscle pain,pharyngeal erythema, red throat, throat redness,cervical lymphad...",1

In [12]:
# Initialize and train the ensemble
# This is the main training call - similar to model.fit() in sklearn or lm() in R
import logging

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Initialize the trainer
trainer = EnsembleTrainer(
    config=ensemble_config,
    output_dir=str(output_dir),
    seed=42,
)

print("Training ensemble model...")
print("This may take a few minutes depending on the LLM response times.")
print()

# Run the training (async)
training_histories = await trainer.fit(train_df)

print("\nTraining complete!")

Training ensemble model...
This may take a few minutes depending on the LLM response times.

/Users/jean/Documents/Research/HACHI/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:2092: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
/Users/jean/Documents/Research/HACHI/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:2150: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(

[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: We are fitting a concept bottleneck model (CBM) to predict whether or not a patient has the flu from their clinical notes. The goal is to identify interpretable yes/no concepts that clinicians can use to predict probability of having the flu.\n\nA meta-concept must be a yes/no question like \"Does the note mention the patient having...?\".\n\nGiven data analysis, these are the top phrases associated with flu:\nfeature_name,coef\nno acute illness,-1.000\nhigh temperature,0.952\nfever,0.952\nbody aches,0.952\nfatigue,0.762\nred throat,0.762\nerythematous pharynx,0.762\nmyalgias,0.762\nno fever,-0.714\nnormal temperature,-0.714\nstable condition,-0.714\ntiredness,0.571\nrunny nose,0.571\ncervical lymphadenopathy,0.571\nswollen lymph nodes,0.571\ncough,0.571\nclear pharynx,-0.571\nnormal vital signs,-0.429\nnasal discharge,0.381\nincreased heart rate,0.381\ndry cough,0.381\nwet cough,0.381\nmalaise,0.381\nstable vitals,-0.286\nproductive cough,0.190\ntachycardia,0.190\nmild tachycardia,0.190\nnasal congestion,0.190\nabsence of cough,-0.143\nno body aches,-0.143\n\n\nYOUR TASK:\nPropose 3 candidate meta-concepts for the CBM.\n\nPropose candidates in JSON format:\n{\n  \"reasoning\": \"Step-by-step explanation\",\n  \"concepts\": [\n    {\n      \"concept\": \"Does the note mention the patient having fever?\",\n      \"is_risk_factor\": true,\n      \"words\": [\"fever\", \"temperature elevated\", \"febrile\"]\n    }\n  ]\n}\n\nFinal answer:"
  ]
}
[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [3.64s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "{\n  \"reasoning\": \"The candidate meta-concepts are derived from the phrases associated with flu symptoms and their corresponding coefficients. A positive coefficient indicates that the presence of the concept is associated with a higher probability of having the flu, while a negative coefficient indicates the opposite. Each proposed concept is framed as a yes/no question to align with the requirements of the concept bottleneck model.\",\n  \"concepts\": [\n    {\n      \"concept\": \"Does the note mention the patient having fever?\",\n      \"is_risk_factor\": true,\n      \"words\": [\"fever\", \"temperature elevated\", \"febrile\"]\n    },\n    {\n      \"concept\": \"Does the note mention the patient having body aches?\",\n      \"is_risk_factor\": true,\n      \"words\": [\"body aches\", \"myalgias\", \"muscle pain\"]\n    },\n    {\n      \"concept\": \"Does the note mention the patient having a high temperature?\",\n      \"is_risk_factor\": true,\n      \"words\": [\"high temperature\", \"elevated temperature\", \"hyperthermia\"]\n    }\n  ]\n}",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "{\n  \"reasoning\": \"The candidate meta-concepts are derived from the phrases associated with flu symptoms and their corresponding coefficients. A positive coefficient indicates that the presence of the concept is associated with a higher probability of having the flu, while a negative coefficient indicates the opposite. Each proposed concept is framed as a yes/no question to align with the requirements of the concept bottleneck model.\",\n  \"concepts\": [\n    {\n      \"concept\": \"Does the note mention the patient having fever?\",\n      \"is_risk_factor\": true,\n      \"words\": [\"fever\", \"temperature elevated\", \"febrile\"]\n    },\n    {\n      \"concept\": \"Does the note mention the patient having body aches?\",\n      \"is_risk_factor\": true,\n      \"words\": [\"body aches\", \"myalgias\", \"muscle pain\"]\n    },\n    {\n      \"concept\": \"Does the note mention the patient having a high temperature?\",\n      \"is_risk_factor\": true,\n      \"words\": [\"high temperature\", \"elevated temperature\", \"hyperthermia\"]\n    }\n  ]\n}",
            "additional_kwargs": {
              "parsed": {
                "lc": 1,
                "type": "not_implemented",
                "id": [
                  "src",
                  "llm_response_types",
                  "CandidateConcepts"
                ],
                "repr": "CandidateConcepts(reasoning='The candidate meta-concepts are derived from the phrases associated with flu symptoms and their corresponding coefficients. A positive coefficient indicates that the presence of the concept is associated with a higher probability of having the flu, while a negative coefficient indicates the opposite. Each proposed concept is framed as a yes/no question to align with the requirements of the concept bottleneck model.', concepts=[CandidateConcept(concept='Does the note mention the patient having fever?', is_risk_factor=True, words=['fever', 'temperature elevated', 'febrile']), CandidateConcept(concept='Does the note mention the patient having body aches?', is_risk_factor=True, words=['body aches', 'myalgias', 'muscle pain']), CandidateConcept(concept='Does the note mention the patient having a high temperature?', is_risk_factor=True, words=['high temperature', 'elevated temperature', 'hyperthermia'])])"
              },
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 224,
                "prompt_tokens": 624,
                "total_tokens": 848,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_name": "gpt-4o-mini-2024-07-18",
              "system_fingerprint": "fp_aa2771c053",
              "id": "chatcmpl-DpaRWeekoqPY3WcDFTn77gaufwreC",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run--f7e70094-20aa-4e49-b71e-9680824503fa-0",
            "usage_metadata": {
              "input_tokens": 624,
              "output_tokens": 224,
              "total_tokens": 848,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 224,
      "prompt_tokens": 624,
      "total_tokens": 848,
      "completion_tokens_details": {
        "accepted_prediction_tokens": 0,
        "audio_tokens": 0,
        "reasoning_tokens": 0,
        "rejected_prediction_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": 0,
        "cached_tokens": 0
      }
    },
    "model_name": "gpt-4o-mini-2024-07-18",
    "system_fingerprint": "fp_aa2771c053",
    "id": "chatcmpl-DpaRWeekoqPY3WcDFTn77gaufwreC",
    "service_tier": "default"
  },
  "run": null,
  "type": "LLMResult"
}
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [0ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [3.64s] Exiting Chain run with output:
[outputs]
DATASET LEN 28

  0%|          | 0/1 [00:00<?, ?it/s]

[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs][chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]

[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence] Entering Chain run with input:
[inputs]
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nnormal vital signs, stable vitals,clear pharynx, throat clear,no acute illness, no current illness\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nnormal temperature, no fever,no cough, absence of cough,no body aches, absence of malaise\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nskin rash, dermatitis,no acute illness, stable condition,clear pharynx, normal throat examination\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nno acute illness, absence of illness,normal vital signs, stable vital signs,clear pharynx, unobstructed throat\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nnormal temperature, no fever,clear pharynx, no throat redness,no acute illness, stable condition\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nfever, high temperature,fatigue, tiredness,body aches, myalgias,runny nose, nasal discharge,mild tachycardia, increased heart rate\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nnormal temperature, no fever,no acute illness, stable condition,no lymphadenopathy, no swollen glands\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nnormal temperature, no fever,clear pharynx, no throat infection,no acute illness, stable condition\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nfever, high temperature,nasal congestion, stuffy nose,wet cough, productive cough,cervical lymphadenopathy, swollen lymph nodes,mild tachycardia, increased heart rate\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nno acute illness, absence of illness,normal vital signs, stable vitals,clear pharynx, no throat inflammation\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nfatigue, tiredness,dry cough, cough,body aches, myalgias,mild tachycardia, increased heart rate,cervical lymphadenopathy, swollen lymph nodes\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nnormal temperature, no fever,no acute illness, absence of symptoms,normal vital signs, stable condition\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nnormal temperature, no fever,no acute illness, stable condition,normal vital signs, healthy status\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nfever, high temperature,wet cough, cough,body aches, myalgias,erythematous pharynx, red throat,cervical lymphadenopathy, swollen lymph nodes\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nfever, high temperature,body aches, myalgias,runny nose, nasal congestion,fatigue, malaise,erythematous pharynx, red throat\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nnormal temperature, 98.6F,clear pharynx, no throat redness,no acute illness, stable condition\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nfever, high temperature,runny nose, nasal discharge,fatigue, tiredness,wet cough, productive cough,cervical lymphadenopathy, swollen lymph nodes\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a helpful assistant\nHuman: You will be given clinical notes and a series of yes/no questions. For each question, answer with 1 (yes) if the information is mentioned in the note, or 0 (no) if it is not. Provide your answers in JSON format with each question mapped to its corresponding answer (0 or 1).\n\nQuestions:\n1 - Does the note mention the patient having fever?\n2 - Does the note mention the patient having body aches?\n3 - Does the note mention the patient having a high temperature?\n\n\nClinical notes:\nno acute illness, absence of illness,normal vital signs, stable vital signs,clear pharynx, unremarkable throat\n\nExample answer: {\n    \"0\": 0,\n    \"1\": 1,\n    \"2\": 0\n}\n\nAnswer all the questions and do not answer with anything else besides valid JSON. Do not add comments to the JSON."
  ]
}
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [

100%|██████████| 1/1 [00:05<00:00,  5.53s/it]

[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [5.47s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "{\"reasoning\":null,\"extractions\":[{\"question\":1,\"reasoning\":\"The note states 'no fever', indicating the patient does not have a fever.\",\"answer\":0},{\"question\":2,\"reasoning\":\"There is no mention of body aches in the clinical notes.\",\"answer\":0},{\"question\":3,\"reasoning\":\"The note mentions 'normal temperature' and 'no fever', indicating the patient does not have a high temperature.\",\"answer\":0}]}",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "{\"reasoning\":null,\"extractions\":[{\"question\":1,\"reasoning\":\"The note states 'no fever', indicating the patient does not have a fever.\",\"answer\":0},{\"question\":2,\"reasoning\":\"There is no mention of body aches in the clinical notes.\",\"answer\":0},{\"question\":3,\"reasoning\":\"The note mentions 'normal temperature' and 'no fever', indicating the patient does not have a high temperature.\",\"answer\":0}]}",
            "additional_kwargs": {
              "parsed": {
                "lc": 1,
                "type": "not_implemented",
                "id": [
                  "src",
                  "llm_response_types",
                  "ExtractResponseList"
                ],
                "repr": "ExtractResponseList(reasoning=None, extractions=[ExtractResponse(question=1, reasoning=\"The note states 'no fever', indicating the patient does not have a fever.\", answer=0.0), ExtractResponse(question=2, reasoning='There is no mention of body aches in the clinical notes.', answer=0.0), ExtractResponse(question=3, reasoning=\"The note mentions 'normal temperature' and 'no fever', indicating the patient does not have a high temperature.\", answer=0.0)])"
              },
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 94,
                "prompt_tokens": 367,
                "total_tokens": 461,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_name": "gpt-4o-mini-2024-07-18",
              "system_fingerprint": "fp_d0b314e02e",
              "id": "chatcmpl-DpaRedcT1rTy8ayyKU4TEhHddrCD2",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "run--1d855e62-6811-4d60-87eb-95db65d07013-0",
            "usage_metadata": {
              "input_tokens": 367,
              "output_tokens": 94,
              "total_tokens": 461,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 94,
      "prompt_tokens": 367,
      "total_tokens": 461,
      "completion_tokens_details": {
        "accepted_prediction_tokens": 0,
        "audio_tokens": 0,
        "reasoning_tokens": 0,
        "rejected_prediction_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": 0,
        "cached_tokens": 0
      }
    },
    "model_name": "gpt-4o-mini-2024-07-18",
    "system_fingerprint": "fp_d0b314e02e",
    "id": "chatcmpl-DpaRedcT1rTy8ayyKU4TEhHddrCD2",
    "service_tier": "default"
  },
  "run": null,
  "type": "LLMResult"
}
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/start] [chain:RunnableSequence > chain:RunnableLambda] Entering Chain run with input:
[inputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [10ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [10ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [9ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [8ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [10ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [9ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [8ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [8ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [8ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [9ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [12ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [8ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [8ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [11ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [8ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [8ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [8ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [12ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [10ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [9ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [8ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [9ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [9ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [12ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [8ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence > chain:RunnableLambda] [8ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.51s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.51s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.51s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.51s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
[chain/end] [chain:RunnableSequence] [5.50s] Exiting Chain run with output:
[outputs]
test_auc 0.5102040816326531

Training complete!

/Users/jean/Documents/Research/HACHI/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jean/Documents/Research/HACHI/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/jean/Documents/Research/HACHI/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

In [13]:
# Display training results
print("Training Results")
print("=" * 60)

for init_seed, history in training_histories.items():
    print(f"\nModel (seed={init_seed}):")
    print(f"  Number of iterations: {history.num_iters}")
    print(f"  Final AUC: {history.get_last_auc():.3f}")
    
    print(f"\n  Learned Concepts:")
    for i, concept in enumerate(history.get_last_concepts()):
        coef = history._coefs[-1][i] if history._coefs else "N/A"
        print(f"    {i+1}. {concept['concept']}")
        if isinstance(coef, (int, float)):
            print(f"       Coefficient: {coef:.3f}")

Training Results
============================================================

Model (seed=1):
  Number of iterations: 1
  Final AUC: 0.604

  Learned Concepts:
    1. Does the note mention the patient having fever?
       Coefficient: -0.438
    2. Does the note mention the patient having body aches?
       Coefficient: 0.328
    3. Does the note mention the patient having a high temperature?
       Coefficient: -0.438

---

# Step 3: Review Results in HTML Viewer

HACHI provides an interactive HTML viewer to explore:
- Individual patient notes and their concept assignments
- Model performance metrics
- Concept coefficients and their interpretations
- Hierarchical clustering of concepts

To generate the viewer, run these commands from the project root:

In [ ]:
# Save viewer configuration
import json

viewer_config = {
    "ui": {
        "title": "HACHI Demo: Flu Detection",
        "encounter_display_name": "Patient",
        "column_display_names": {
            "patient_id": "Patient ID",
            "y": "Flu Outcome"
        }
    },
    "dataset": {
        "id_column": "patient_id",
        "note_column": "sentence",
        "summary_column": "llm_output",
        "metadata_columns": ["y"]
    },
    "prompts": {
        "prompts_directory": str(project_root / "notebooks" / "prompts"),
        "step1_summary": ["flu_keyphrases.txt"],
        "step2_extraction": ["concept_questions.txt"],
        "step3_initialization": ["baseline_init.txt"],
        "step4_generation": ["bayesian_iter.txt"]
    }
}

config_path = output_dir / "viewer_config.json"
with open(config_path, "w") as f:
    json.dump(viewer_config, f, indent=2)

print(f"Viewer config saved to: {config_path}")

In [ ]:
# Print the commands to run for generating the viewer
print("Run these commands from the project root directory:")
print()
print("# 1. Export data for the viewer")
print(f"python ui/export_standalone.py export \\")
print(f"    --llm-summaries {output_dir / 'keyphrases.csv'} \\")
print(f"    --initializations init_seed_1:{output_dir / 'ensemble' / 'init_seed_1'} \\")
print(f"    --config {output_dir / 'viewer_config.json'} \\")
print(f"    --output-dir {output_dir / 'viewer'}")
print()
print("# 2. Build the standalone HTML viewer")
print(f"python ui/build_standalone.py --output {output_dir / 'viewer' / 'viewer.html'}")
print()
print("# 3. Open the viewer in your browser and load:")
print(f"#    - {output_dir / 'viewer' / 'data.csv'}")
print(f"#    - {output_dir / 'viewer' / 'config.json'}")

---

# Summary

This demo showed the three main steps of HACHI:

1. **Keyphrase Extraction**: Used an LLM to extract clinically relevant terms from patient notes
2. **Ensemble Training**: Trained concept bottleneck models that learn interpretable yes/no concepts
3. **Result Review**: Exported results to an interactive HTML viewer

## Next Steps

To use HACHI on your own data:

1. Prepare a CSV with clinical notes and outcomes
2. Create custom prompts for your clinical domain
3. Run the pipeline with appropriate parameters
4. Review results and iterate with clinical expert feedback

See the [README](../README.md) for detailed usage instructions and the `exp_aki/` directory for a real-world example.